/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.anshdawda.discarded;

import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatDarkLaf;

/**
 *
 * @author anshd
 */
public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JTextPane();
        textFieldUsername = new javax.swing.JTextField();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        toggleButtonPassword = new javax.swing.JButton();
        buttonHelp = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonSubmit = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        labelNewUser = new javax.swing.JLabel();
        labelClickHere = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        title.setEditable(false);
        title.setBorder(null);
        title.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        title.setText("Library\nManagement\nSystem");
        title.setAutoscrolls(false);
        title.setFocusable(false);
        title.setOpaque(false);
        title.setRequestFocusEnabled(false);

        labelUsername.setText("Username:");
        labelUsername.setToolTipText("");

        labelPassword.setText("Password:");

        toggleButtonPassword.setText("Show Password");
        toggleButtonPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonPasswordActionPerformed(evt);
            }
        });

        buttonHelp.setText("?");
        buttonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHelpActionPerformed(evt);
            }
        });

        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        labelNewUser.setText("New User?");

        labelClickHere.setText("Click Here");
        labelClickHere.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelClickHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelClickHereMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField)
                            .addComponent(textFieldUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toggleButtonPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNewUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelClickHere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsername)
                    .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword)
                    .addComponent(toggleButtonPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClear)
                    .addComponent(buttonSubmit)
                    .addComponent(buttonExit)
                    .addComponent(labelNewUser)
                    .addComponent(labelClickHere))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleButtonPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonPasswordActionPerformed
        // TODO add your handling code here:
        if (passwordField.getEchoChar() == (char) 0) {
            passwordField.setEchoChar('\u2022');
            toggleButtonPassword.setText("Show Password");
        } else {
            passwordField.setEchoChar((char) 0);
            toggleButtonPassword.setText("Hide Password");
        }
    }//GEN-LAST:event_toggleButtonPasswordActionPerformed

    private void buttonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHelpActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
                null,
                "Username:\n"
                + "1. The username length should have greater than 6 and less than 25 characters.\n"
                + "2. The username shouldn't contain any spances.\n"
                + "\n"
                + "Password:\n"
                + "1. The password should be atleast 8 characters long.\n"
                + "2. The password should contain atleast one uppercase letter.\n"
                + "3. The password should contain atleast one of the following symbols - '!', '@' and/or '#'.",
                "Username & Password help",
                JOptionPane.QUESTION_MESSAGE
        );
    }//GEN-LAST:event_buttonHelpActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(buttonClear, "Are you sure?", "Clear", JOptionPane.YES_NO_OPTION) == 0) {
            textFieldUsername.setText("");
            passwordField.setText("");
        }
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
        String username = textFieldUsername.getText();
        String password = String.valueOf(passwordField.getPassword());
        boolean areAllFieldsFilled
                = !username.isBlank()
                && !password.isBlank();
        if (areAllFieldsFilled) {
            String passwordMessage = isValidPassword(password);
            if (!isValidUsername(username)) {
                JOptionPane.showMessageDialog(
                        buttonSubmit,
                        "Username does not exist!",
                        "Invalid Username",
                        JOptionPane.ERROR_MESSAGE
                );
            } else if (passwordMessage != null) {
                JOptionPane.showMessageDialog(
                        buttonSubmit,
                        passwordMessage,
                        "Invalid Password",
                        JOptionPane.ERROR_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        buttonSubmit,
                        "Successfully logged in!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
        } else {
            JOptionPane.showMessageDialog(
                    buttonSubmit,
                    "The form data is missing.",
                    "Empty fields",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(buttonExit, "Are you sure?", "Exit", JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(ABORT);
        }
    }//GEN-LAST:event_buttonExitActionPerformed

    private void labelClickHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelClickHereMouseClicked
        // TODO add your handling code here:
        new RegisterWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelClickHereMouseClicked

    boolean isValidUsername(String username) {
        return (6 <= username.length() && username.length() <= 25);
    }

    String isValidPassword(String password) {
        if (password.length() < 8
                || password.chars().filter(Character::isUpperCase).findAny().isEmpty()
                || !(password.contains("!") || password.contains("@") || password.contains("#"))) {
            return "Invalid password!";
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        FlatDarkLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JLabel labelClickHere;
    private javax.swing.JLabel labelNewUser;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField textFieldUsername;
    private javax.swing.JTextPane title;
    private javax.swing.JButton toggleButtonPassword;
    // End of variables declaration//GEN-END:variables
}
