/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.anshdawda;

/**
 *
 * @author anshd
 */
public class Content extends javax.swing.JInternalFrame {

    /**
     * Creates new form Content
     */
    public Content() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        introductionPanel = new javax.swing.JPanel();
        titleTextPane = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        featuresPanel = new javax.swing.JPanel();
        featuresTabbedPanel = new javax.swing.JTabbedPane();
        accountsPanel = new javax.swing.JPanel();
        bookManagementPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setTitle("Contents");

        titleTextPane.setEditable(false);
        titleTextPane.setBorder(null);
        titleTextPane.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        titleTextPane.setText("Library\nManagement\nSystem");
        titleTextPane.setAutoscrolls(false);
        titleTextPane.setFocusable(false);
        titleTextPane.setOpaque(false);

        javax.swing.GroupLayout introductionPanelLayout = new javax.swing.GroupLayout(introductionPanel);
        introductionPanel.setLayout(introductionPanelLayout);
        introductionPanelLayout.setHorizontalGroup(
            introductionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introductionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(introductionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(introductionPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(introductionPanelLayout.createSequentialGroup()
                        .addComponent(titleTextPane, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addGap(393, 393, 393))))
        );
        introductionPanelLayout.setVerticalGroup(
            introductionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introductionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Introduction", introductionPanel);

        featuresTabbedPanel.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        featuresTabbedPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout accountsPanelLayout = new javax.swing.GroupLayout(accountsPanel);
        accountsPanel.setLayout(accountsPanelLayout);
        accountsPanelLayout.setHorizontalGroup(
            accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        accountsPanelLayout.setVerticalGroup(
            accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        featuresTabbedPanel.addTab("Accounts", accountsPanel);

        javax.swing.GroupLayout bookManagementPanelLayout = new javax.swing.GroupLayout(bookManagementPanel);
        bookManagementPanel.setLayout(bookManagementPanelLayout);
        bookManagementPanelLayout.setHorizontalGroup(
            bookManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        bookManagementPanelLayout.setVerticalGroup(
            bookManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        featuresTabbedPanel.addTab("Book Management", bookManagementPanel);

        javax.swing.GroupLayout featuresPanelLayout = new javax.swing.GroupLayout(featuresPanel);
        featuresPanel.setLayout(featuresPanelLayout);
        featuresPanelLayout.setHorizontalGroup(
            featuresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(featuresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(featuresTabbedPanel)
                .addContainerGap())
        );
        featuresPanelLayout.setVerticalGroup(
            featuresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(featuresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(featuresTabbedPanel)
                .addContainerGap())
        );

        tabbedPane.addTab("Features", featuresPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountsPanel;
    private javax.swing.JPanel bookManagementPanel;
    private javax.swing.JPanel featuresPanel;
    private javax.swing.JTabbedPane featuresTabbedPanel;
    private javax.swing.JPanel introductionPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextPane titleTextPane;
    // End of variables declaration//GEN-END:variables
}
